name: API CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'api/**'

jobs:
  api-pipeline:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Check code formatting
      run: npm run format -- --check
      
    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm run test

    - name: Run e2e tests
      run: npm run test:e2e

    - name: Run tests with coverage
      run: npm run test:cov

    - name: Build application
      run: npm run build

    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./api/coverage/lcov.info
        flags: api
        name: api-coverage
