name: Web CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./web

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './web/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run format check
      run: npm run format -- --check

    - name: Type checking
      run: npx tsc --noEmit

    - name: Build project
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: ./web/dist/
        retention-days: 7
